version: '3'

services:
  db:
    image: mariadb:10.9.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    networks:
      - crrow
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "8082:80"
    networks:
      - crrow
    depends_on:
      - db
    restart: always

  web:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ./web/build/distributions/:/usr/local/apache2/htdocs/
    restart: always

networks:
  crrow:

volumes:
  db_data: